version: '3.8'

services:
  danmaku-collector:
    image: ghcr.hmr.sh/robinwongm/danmaku-collector:latest
    volumes:
      - ./.env:/app/.env
      - ./data:/app/data
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
