name: Docker Build

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Receiver
        id: meta-receiver
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch,suffix=-receiver
            type=ref,event=pr,suffix=-receiver
            type=semver,pattern={{version}}-receiver
            type=sha,suffix=-receiver

      - name: Extract metadata (tags, labels) for Processor
        id: meta-processor
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch,suffix=-processor
            type=ref,event=pr,suffix=-processor
            type=semver,pattern={{version}}-processor
            type=sha,suffix=-processor

      - name: Build and push Receiver image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: packages/receiver/Dockerfile
          push: true
          tags: ${{ steps.meta-receiver.outputs.tags }}
          labels: ${{ steps.meta-receiver.outputs.labels }}

      - name: Build and push Processor image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: packages/processor/Dockerfile
          push: true
          tags: ${{ steps.meta-processor.outputs.tags }}
          labels: ${{ steps.meta-processor.outputs.labels }}